// Barrel for the Drizzle schema.
//
// ./auth is generated by the Better Auth CLI (`pnpm auth:generate`) and must
// not be hand-edited; ./app holds the application tables. Keeping them in
// separate files means regenerating after a Better Auth upgrade cannot
// clobber our own tables.
export * from './auth'
export * from './app'
